const KEY='nutrihome-v1';
const DAYS=['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo'];
const TYPES=[['breakfast','Desayuno'],['lunch','Comida'],['snack','Merienda'],['dinner','Cena']];
const recipes=[
{id:'r1',title:'Avena cremosa con plátano',emoji:'🥣',types:['breakfast'],min:10,kcal:430,protein:17,rating:4.8,diets:['vegetarian','lacto','vegan'],ingredients:[['Avena',70,'g'],['Bebida vegetal',250,'ml'],['Plátano',1,'ud']]},
{id:'r2',title:'Curry de garbanzos y espinacas',emoji:'🍛',types:['lunch','dinner'],min:28,kcal:610,protein:24,rating:4.9,diets:['vegetarian','lacto','vegan'],ingredients:[['Garbanzos cocidos',220,'g'],['Espinacas',100,'g'],['Arroz basmati',70,'g']]},
{id:'r3',title:'Pasta al pesto con tomate',emoji:'🍝',types:['lunch','dinner'],min:20,kcal:690,protein:23,rating:4.7,diets:['vegetarian','lacto'],dairy:true,ingredients:[['Pasta',100,'g'],['Tomate cherry',120,'g'],['Pesto',35,'g']]},
{id:'r4',title:'Tacos de frijoles y aguacate',emoji:'🌮',types:['lunch','dinner'],min:18,kcal:560,protein:20,rating:4.8,diets:['vegetarian','lacto','vegan'],ingredients:[['Tortillas',3,'ud'],['Frijoles cocidos',180,'g'],['Aguacate',1,'ud']]},
{id:'r5',title:'Yogur con frutos rojos y nueces',emoji:'🫐',types:['breakfast','snack'],min:5,kcal:320,protein:19,rating:4.6,diets:['vegetarian','lacto'],dairy:true,ingredients:[['Yogur griego',200,'g'],['Frutos rojos',100,'g'],['Nueces',20,'g']]},
{id:'r6',title:'Buddha bowl de tofu',emoji:'🥗',types:['lunch','dinner'],min:32,kcal:650,protein:34,rating:4.9,diets:['vegetarian','lacto','vegan'],ingredients:[['Tofu',180,'g'],['Quinoa',75,'g'],['Brócoli',130,'g']]}
];
function fresh(){let week={};DAYS.forEach(d=>week[d]={breakfast:null,lunch:null,snack:null,dinner:null});return{route:'home',day:DAYS[0],profile:{kcal:2100,protein:100,diet:'vegetarian',noEgg:true,noDairy:false},week,pantry:[{id:'p1',name:'Arroz basmati',qty:350,unit:'g',min:150},{id:'p2',name:'Garbanzos cocidos',qty:100,unit:'g',min:200}],shopping:[],custom:[]}}
let s;try{s={...fresh(),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{s=fresh()};
const $=q=>document.querySelector(q), app=$('#app'), title=$('#screen-title');
const save=()=>localStorage.setItem(KEY,JSON.stringify(s));
const all=()=>[...recipes,...s.custom];
const allowed=r=>!(s.profile.diet==='vegan'&&!r.diets.includes('vegan'))&&!(s.profile.noDairy&&r.dairy)&&!(s.profile.noEgg&&r.egg);
const get=id=>all().find(r=>r.id===id);
function nav(r){s.route=r;save();render()}
document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>nav(b.dataset.route));
function shell(name,html){title.textContent=name;app.innerHTML=html;document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.route===s.route));}
function card(r,extra=''){return `<div class="card"><div class="meal-card"><div class="meal-emoji">${r.emoji||'🍽️'}</div><div><h3>${r.title}</h3><div class="meal-meta"><span>${r.min} min</span><span>${r.kcal} kcal</span><span>${r.protein} g proteína</span><span>★ ${r.rating||'—'}</span></div></div>${extra}</div></div>`}
function random(day,type){let a=all().filter(r=>allowed(r)&&r.types.includes(type));if(!a.length)return;s.week[day][type]=a[Math.floor(Math.random()*a.length)].id;save();render()}
function home(){let meals=Object.values(s.week[s.day]).map(get).filter(Boolean), kcal=meals.reduce((a,r)=>a+r.kcal,0), low=s.pantry.filter(x=>+x.qty<=+x.min).length;shell('Inicio',`<section class="hero"><h2>Hola 👋</h2><p>Planifica tu alimentación usando lo que ya tienes en casa.</p><div class="stats"><div class="stat"><strong>${kcal}</strong><span>kcal hoy</span></div><div class="stat"><strong>${meals.length}/4</strong><span>comidas</span></div><div class="stat"><strong>${low}</strong><span>stock bajo</span></div></div></section><div class="grid two"><button class="btn" onclick="nav('week')">Plan semanal</button><button class="btn secondary" onclick="nav('shopping')">Lista de compra</button></div><div class="section-title"><h2>${s.day}</h2></div>${TYPES.map(([k,n])=>{let r=get(s.week[s.day][k]);return r?card(r,`<button class="icon-btn" onclick="random('${s.day}','${k}')">↻</button>`):`<div class="card space-between"><div><b>${n}</b><div class="muted small">Sin plato</div></div><button class="btn secondary" onclick="random('${s.day}','${k}')">Sugerir</button></div>`}).join('')}`)}
function week(){shell('Plan semanal',`<div class="day-tabs">${DAYS.map(d=>`<button class="day-tab ${d===s.day?'active':''}" onclick="s.day='${d}';save();render()">${d.slice(0,3)}</button>`).join('')}</div><div class="section-title"><h2>${s.day}</h2><button class="btn" onclick="TYPES.forEach(x=>random('${s.day}',x[0]))">Generar día</button></div>${TYPES.map(([k,n])=>{let r=get(s.week[s.day][k]);return r?card(r,`<button class="icon-btn" onclick="random('${s.day}','${k}')">↻</button>`):`<div class="card space-between"><b>${n}</b><button class="btn secondary" onclick="random('${s.day}','${k}')">Aleatorizar</button></div>`}).join('')}`)}
function recipeView(){shell('Recetas',`<div class="searchbar"><input id="q" placeholder="Buscar receta…"><button class="btn" onclick="addRecipe()">＋</button></div><div class="filters"><button class="chip" onclick="filterRecipes(15)">≤15 min</button><button class="chip" onclick="filterRecipes(30)">≤30 min</button><button class="chip" onclick="filterRecipes(999)">Todas</button></div><div id="recipe-list" class="recipe-grid">${all().filter(allowed).map(r=>card(r)).join('')}</div>`);$('#q').oninput=e=>filterRecipes(999,e.target.value)}
function filterRecipes(max,q=''){q=q.toLowerCase();$('#recipe-list').innerHTML=all().filter(r=>allowed(r)&&r.min<=max&&r.title.toLowerCase().includes(q)).map(r=>card(r)).join('')||'<div class="empty">No hay coincidencias.</div>'}
function addRecipe(){let name=prompt('Nombre de la receta');if(!name)return;let url=prompt('URL de origen (Instagram/web), opcional')||'';s.custom.push({id:'c'+Date.now(),title:name,emoji:'🍽️',types:['lunch','dinner'],min:30,kcal:500,protein:20,rating:null,diets:['vegetarian','lacto','vegan'],ingredients:[],url});save();recipeView()}
function pantry(){shell('Despensa',`<div class="section-title"><h2>Lo que tienes en casa</h2><button class="btn" onclick="addPantry()">＋ Añadir</button></div>${s.pantry.map(p=>`<div class="card pantry-row"><div><h3>${p.name}</h3><div class="muted small">${p.qty} ${p.unit} · aviso ≤ ${p.min}</div><div class="progress ${+p.qty<=+p.min?'low':''}"><span style="width:${Math.min(100,+p.qty/(+p.min*2||1)*100)}%"></span></div></div><button class="icon-btn" onclick="usePantry('${p.id}')">−</button></div>`).join('')||'<div class="empty">Despensa vacía.</div>'}`)}
function addPantry(){let name=prompt('Producto');if(!name)return;let qty=+(prompt('Cantidad')||1),unit=prompt('Unidad: g, ml, ud…')||'ud',min=+(prompt('Avisar cuando quede menos de…')||1);s.pantry.push({id:'p'+Date.now(),name,qty,unit,min});save();pantry()}
function usePantry(id){let p=s.pantry.find(x=>x.id===id);p.qty=Math.max(0,+p.qty-(p.unit==='ud'?1:50));save();pantry()}
function generateShopping(){let map={};DAYS.forEach(d=>Object.values(s.week[d]).forEach(id=>{let r=get(id);r?.ingredients.forEach(([n,q,u])=>{let k=n.toLowerCase()+'|'+u;map[k]=map[k]||{name:n,qty:0,unit:u};map[k].qty+=q})}));s.shopping=Object.values(map).map(x=>{let p=s.pantry.find(p=>p.name.toLowerCase()===x.name.toLowerCase()&&p.unit===x.unit);return{...x,id:'s'+Math.random(),qty:Math.max(0,x.qty-(p?.qty||0)),done:false}}).filter(x=>x.qty>0);s.pantry.filter(p=>+p.qty<=+p.min).forEach(p=>{if(!s.shopping.some(x=>x.name===p.name))s.shopping.push({id:'s'+Math.random(),name:p.name,qty:Math.max(1,p.min*2-p.qty),unit:p.unit,done:false})});save();shopping()}
function shopping(){shell('Lista de compra',`<button class="btn" onclick="generateShopping()">Generar desde menú + despensa</button><div class="section-title"><h2>Compra</h2></div>${s.shopping.map(x=>`<div class="card shopping-row ${x.done?'done':''}"><label class="check"><input type="checkbox" ${x.done?'checked':''} onchange="toggleShop('${x.id}',this.checked)"><span><b>${x.name}</b><br><small class="muted">${x.qty} ${x.unit}</small></span></label></div>`).join('')||'<div class="empty">Genera la lista cuando tengas tu menú.</div>'}`)}
function toggleShop(id,v){let x=s.shopping.find(x=>x.id===id);x.done=v;if(v){let p=s.pantry.find(p=>p.name.toLowerCase()===x.name.toLowerCase()&&p.unit===x.unit);p?p.qty+=x.qty:s.pantry.push({id:'p'+Date.now(),name:x.name,qty:x.qty,unit:x.unit,min:x.unit==='ud'?1:100})}save();shopping()}
function profile(){let p=s.profile;shell('Perfil y nutrición',`<div class="card"><div class="form-group"><label>Objetivo kcal/día</label><input id="kcal" type="number" value="${p.kcal}"></div><div class="form-group"><label>Proteína g/día</label><input id="protein" type="number" value="${p.protein}"></div><div class="form-group"><label>Dieta</label><select id="diet"><option value="vegetarian">Vegetariana</option><option value="lacto">Lacto-vegetariana</option><option value="ovo">Ovo-vegetariana</option><option value="vegan">Vegana</option></select></div><label class="check"><input id="egg" type="checkbox" ${p.noEgg?'checked':''}> Excluir huevo</label><br><label class="check"><input id="dairy" type="checkbox" ${p.noDairy?'checked':''}> Excluir lácteos</label><hr><button class="btn" onclick="saveProfile()">Guardar</button></div>`);$('#diet').value=p.diet}
function saveProfile(){s.profile={kcal:+$('#kcal').value,protein:+$('#protein').value,diet:$('#diet').value,noEgg:$('#egg').checked,noDairy:$('#dairy').checked};save();profile()}
function render(){({home,week,recipes:recipeView,pantry,shopping,profile}[s.route]||home)()}
window.nav=nav;window.s=s;window.save=save;window.render=render;window.random=random;window.filterRecipes=filterRecipes;window.addRecipe=addRecipe;window.addPantry=addPantry;window.usePantry=usePantry;window.generateShopping=generateShopping;window.toggleShop=toggleShop;window.saveProfile=saveProfile;
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
let deferred;addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;$('#install-btn').hidden=false});$('#install-btn').onclick=async()=>{if(deferred){deferred.prompt();deferred=null;$('#install-btn').hidden=true}};
render();
